version: 0.2

env:
  variables:
    BUCKET_NAME: "schoolcrm-dev-appreact-cloud-build"
    AWS_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "🚀 Iniciando instalación..."
      - npm install

  build:
    commands:
      - echo "⚙️ Compilando la aplicación..."
      - npm run build

  post_build:
    commands:
    - echo "📤 Subiendo archivos a S3..."
    - aws s3 sync dist/ s3://$BUCKET_NAME --delete

artifacts:
  files:
    - '**/*'
  discard-paths: yes
